#pragma once

#include <Buffer.h>
#include <AAATypes.h>


enum eChannelToClient
{
	eCHANNEL_CLIENT_PLAYER_INFO				= 4001, 
	eCHANNEL_CLIENT_PLAYER_CHARACTER		= 4002, 
	eCHANNEL_CLIENT_PLAYER_EQUIP			= 4003, 
	eCHANNEL_CLIENT_PLAYER_MONSTER			= 4004, 
	eCHANNEL_CLIENT_PLAYER_TEAM				= 4005, 
	eCHANNEL_CLIENT_PLAYER_INVENTORY		= 4006, 
	eCHANNEL_CLIENT_DUPLICATE				= 4007, 
	eCHANNEL_CLIENT_CHECK_NICKNAME			= 4008, 
	eCHANNEL_CLIENT_SELECT_NEW_CHARACTER	= 4009, 
	eCHANNEL_CLIENT_PLAYER_MAP				= 4010, 
	eCHANNEL_CLIENT_CREATE_MULTI_ROOM		= 4011, 
	eCHANNEL_CLIENT_REMOVE_MULTI_ROOM		= 4012, 
	eCHANNEL_CLIENT_MULTI_GAME_START		= 4013, 
// 	eCHANNEL_CLIENT_CREATE_SINGLE_ROOM		= 4014, 
// 	eCHANNEL_CLIENT_SINGLE_GAME_START		= 4015, 

	eCHANNEL_CLIENT_END_TURN				= 4016, 
	eCHANNEL_CLIENT_ACQUIRE_MONSTER			= 4017, 
	eCHANNEL_CLIENT_THROW_MOSNTER			= 4018, 
	eCHANNEL_CLIENT_MOVE_PLAYER				= 4019,		// eCLIENT_CHANNEL_DICE_CAST 대응
	eCHANNEL_CLIENT_PLACE_MONSTER			= 4020, 
	eCHANNEL_CLIENT_BATTLE_LAND				= 4021, 
	eCHANNEL_CLIENT_SELL_LAND_WAIT			= 4022, 
	eCHANNEL_CLIENT_SELL_LAND				= 4023, 

	eCHANNEL_CLIENT_NEXT_STEP				= 4024, 
	eCHANNEL_CLIENT_GAME_RESULT				= 4025, 

	eCHANNEL_CLIENT_SINGLE_GAME_START		= 4026, 
	eCHANNEL_CLIENT_SINGLE_RESULT			= 4027, 

	eCHANNEL_CLIENT_FRIEND					= 4028, 
	eCHANNEL_CLIENT_RECOMMEND_FRIEND		= 4029, 
	eCHANNEL_CLIENT_FRIEND_ACTION			= 4030, 
	eCHANNEL_CLIENT_FRIEND_SEARCH			= 4031, 

	eCHANNEL_CLIENT_BUY_CHARACTER			= 4032, 
	eCHANNEL_CLIENT_PULL_MONSTER			= 4033, 
	eCHANNEL_CLIENT_BUY_DICE				= 4034, 
	eCHANNEL_CLIENT_BUY_ITEM				= 4035, 
	eCHANNEL_CLIENT_SELL_MONSTER			= 4036, 
	eCHANNEL_CLIENT_SELL_ITEM				= 4037, 

	eCHANNEL_CLIENT_PLAYER_DICE				= 4038, 

	eCHANNEL_CLIENT_CHANGE_CHARACTER		= 4039, 
	eCHANNEL_CLIENT_CHANGE_DICE				= 4040, 
	eCHANNEL_CLIENT_CHANGE_LEADER_MONSTER	= 4041, 
	eCHANNEL_CLIENT_ADD_TEAM_MONSTER		= 4042, 
	eCHANNEL_CLIENT_REMOVE_TEAM_MONSTER		= 4043, 
	eCHANNEL_CLIENT_EXTEND_EQUIP_COUNT		= 4044, 
	eCHANNEL_CLIENT_ATTACH_EQUIP_ITEM		= 4045, 
	eCHANNEL_CLIENT_DETACH_EQUIP_ITEM		= 4046, 
	eCHANNEL_CLIENT_POST					= 4047, 
	eCHANNEL_CLIENT_POST_RECV				= 4048, 
	eCHANNEL_CLIENT_POST_SEND				= 4049, 
	eCHANNEL_CLIENT_POST_SEND_DAILY_HEART	= 4050, 
};

enum eClientToChannel
{
	eCLIENT_CHANNEL_CHARACTER				= 5001, 
	eCLIENT_CHANNEL_EQUIP					= 5002, 
	eCLIENT_CHANNEL_MONSTER					= 5003, 
	eCLIENT_CHANNEL_TEAM					= 5004, 
	eCLIENT_CHANNEL_INVENTORY				= 5005, 
	eCLIENT_CHANNEL_CHECK_NICKNAME			= 5006, 
	eCLIENT_CHANNEL_SELECT_NEW_CHARACTER	= 5007, 
	eCLIENT_CHANNEL_MAP						= 5008, 
	eCLIENT_CHANNEL_CREATE_MULTI_ROOM		= 5009, 
	eCLIENT_CHANNEL_REMOVE_MULTI_ROOM		= 5010, 
	eCLIENT_CHANNEL_MULTI_GAME_START		= 5011, 
//	eCLIENT_CHANNEL_CREATE_SINGLE_ROOM		= 5012, 
//	eCLIENT_CHANNEL_SINGLE_GAME_START		= 5013, 

	eCLIENT_CHANNEL_END_TURN				= 5014, 
	eCLIENT_CHANNEL_THROW_MONSTER			= 5015, 
	eCLIENT_CHANNEL_DICE_CAST				= 5016, 
	eCLIENT_CHANNEL_PLACE_MONSTER			= 5017, 
//	eCLIENT_CHANNEL_PLACE_FRIEND			= 5018,		// 응답은 eCHANNEL_CLIENT_PLACE_MONSTER
	eCLIENT_CHANNEL_BATTLE_LAND				= 5019, 
	eCLIENT_CHANNEL_SELL_LAND				= 5020, 

	eCLIENT_CHANNEL_BROADCAST_ACK			= 5021,		// broadcast 응답 패킷

	eCLIENT_CHANNEL_SINGLE_GAME_START		= 5022, 
	eCLIENT_CHANNEL_SINGLE_ACTTION			= 5023, 
	eCLIENT_CHANNEL_SINGLE_RESULT			= 5024, 

	eCLIENT_CHANNEL_FRIEND					= 5025, 
	eCLIENT_CHANNEL_RECOMMEND_FRIEND		= 5026, 
	eCLIENT_CHANNEL_FRIEND_ACTION			= 5027, 
	eCLIENT_CHANNEL_FRIEND_SEARCH			= 5028, 

	eCLIENT_CHANNEL_BUY_CHARACTER			= 5029, 
	eCLIENT_CHANNEL_PULL_MONSTER			= 5030, 
	eCLIENT_CHANNEL_BUY_DICE				= 5031, 
	eCLIENT_CHANNEL_BUY_ITEM				= 5032, 
	eCLIENT_CHANNEL_SELL_MONSTER			= 5033, 
	eCLIENT_CHANNEL_SELL_ITEM				= 5034, 

	eCLIENT_CHANNEL_DICE					= 5035, 

	eCLIENT_CHANNEL_CHANGE_CHARACTER		= 5035, 
	eCLIENT_CHANNEL_CHANGE_DICE				= 5036, 
	eCLIENT_CHANNEL_CHANGE_LEADER_MONSTER	= 5037, 
	eCLIENT_CHANNEL_ADD_TEAM_MONSTER		= 5038, 
	eCLIENT_CHANNEL_REMOVE_TEAM_MONSTER		= 5039, 
	eCLIENT_CHANNEL_EXTEND_EQUIP_COUNT		= 5040, 
	eCLIENT_CHANNEL_ATTACH_EQUIP_ITEM		= 5041, 
	eCLIENT_CHANNEL_DETACH_EQUIP_ITEM		= 5042, 
	eCLIENT_CHANNEL_POST					= 5043, 
	eCLIENT_CHANNEL_POST_RECV				= 5044, 
	eCLIENT_CHANNEL_POST_SEND				= 5045, 
	eCLIENT_CHANNEL_POST_SEND_DAILY_HEART	= 5046, 
};